### PR TITLE
Some grammar changes

### PR DESCRIPTION
**Pull request by sayyidyofa**

### CODE REVIEW

**Comment by yuesha-yc** [comment]
I would like to merge this if you can help to fix more grammar or polishing issues in the quest book or research translations. Otherwise this readme typo can be fixed simply

**Comment by sayyidyofa** [comment]
You are right! It seems lazy of me to only include the readme in a PR. I'll see what I can do

**Comment by sayyidyofa** [comment]
I added some grammar fixes and polish some word choices. I was intrigued to insert my name to the translations but I decide not to do that. I will let the main developers consider my contributions

When I look at the language files, I see that this modpack is inspired by Frostpunk, TerraFirmaCraft, Create, IE, and genshin. Very cool! I played all of them. There are some translations that I can't edit because I need to know the context, this can be achieved when I play the modpack further.

Cheers. let me know if you find anything wrong

**Review by yuesha-yc — APPROVED** [review]

**Comment by yuesha-yc** [comment]
Thanks for the help, I fixed several typo and will merge this. Recommend you to join discord so that I can give you translation role and for future contribution.

**Comment by sayyidyofa** [comment]
Thank you! If I may add one more question, should I just add the PR link in my self intro message?

**Pull request merged**
